// Vercel Serverless Function: /api/timetable
//
// Timetables are generated by the colour-aware Python job and stored in
// MongoDB.  This endpoint deliberately does not read or parse Google Sheets:
// the public Sheets endpoint does not expose fills, so it cannot safely assign
// a class to its cohort.

const MONGO_CACHE_KEY = Symbol.for("compiler2.mongo.client.cjs");
const SCHOOLS = new Set(["computing", "engineering", "business"]);

function getMongoDb() {
  const uri = process.env.MONGODB_URI;
  if (!uri) return Promise.reject(new Error("MONGODB_URI is not set"));

  if (!globalThis[MONGO_CACHE_KEY]) {
    const { MongoClient } = require("mongodb");
    globalThis[MONGO_CACHE_KEY] = new MongoClient(uri, {
      serverSelectionTimeoutMS: 5000,
      connectTimeoutMS: 5000,
      maxPoolSize: 10,
      minPoolSize: 0,
    }).connect().catch((err) => {
      globalThis[MONGO_CACHE_KEY] = null;
      throw err;
    });
  }

  return globalThis[MONGO_CACHE_KEY].then((client) =>
    client.db(process.env.MONGODB_DB || "compiler2")
  );
}

function countEntries(tt) {
  let count = 0;
  for (const batches of Object.values(tt || {})) {
    for (const sections of Object.values(batches || {})) {
      for (const days of Object.values(sections || {})) {
        for (const entries of Object.values(days || {})) count += (entries || []).length;
      }
    }
  }
  return count;
}

async function loadTimetable(school) {
  const db = await getMongoDb();
  const row = await db.collection("documents").findOne(
    { _id: `timetables/${school}` },
    { projection: { data: 1, updatedAt: 1 } },
  );
  const data = row?.data;
  if (!data?.tt || typeof data.tt !== "object") return null;
  return {
    tt: data.tt,
    count: Number.isFinite(data.count) ? data.count : countEntries(data.tt),
    generatedAt: data.generatedAt || null,
    storedAt: row.updatedAt || null,
  };
}

function normaliseRoom(room) {
  const value = String(room || "").trim().toUpperCase().replace(/\s+/g, " ");
  const match = value.match(/^([CD])\s*-?\s*(\d{3}|IT\s*LAB\s*\d+|MARGALA\s*\d+|RAWAL\s*\d+|GPU\s*LAB)/);
  return match ? `${match[1]}-${match[2].replace(/\s+/g, " ")}` : value;
}

function isCDRoom(room) {
  return /^[CD]-(?:\d{3}|IT LAB \d+|MARGALA \d+|RAWAL \d+|GPU LAB)/.test(room);
}

// Free Rooms uses the same generated timetable, rather than a separate,
// colour-blind Google Sheets parser.
function buildCDRoomOccupancy(tt) {
  const occupancy = {};
  let count = 0;

  for (const [dept, batches] of Object.entries(tt || {})) {
    for (const [batch, sections] of Object.entries(batches || {})) {
      for (const [section, days] of Object.entries(sections || {})) {
        for (const [day, entries] of Object.entries(days || {})) {
          for (const entry of entries || []) {
            const room = normaliseRoom(entry.location);
            if (!isCDRoom(room) || !entry.time) continue;
            const slots = occupancy[day] ??= {};
            const roomEntries = slots[room] ??= [];
            if (roomEntries.some((item) => item.time === entry.time && item.course === entry.name)) continue;
            roomEntries.push({
              course: entry.name || "",
              dept,
              batch,
              section,
              time: entry.time,
            });
            count++;
          }
        }
      }
    }
  }
  return { occupancy, count };
}

module.exports = async (req, res) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, OPTIONS");
  res.setHeader("Cache-Control", "no-store");
  if (req.method === "OPTIONS") return res.status(204).end();
  if (req.method !== "GET") return res.status(405).json({ ok: false, error: "Method not allowed" });

  try {
    if (req.query?.rooms === "cd") {
      const timetable = await loadTimetable("computing");
      if (!timetable) {
        return res.status(503).json({ ok: false, error: "Timetable data is unavailable in MongoDB" });
      }
      const { occupancy, count } = buildCDRoomOccupancy(timetable.tt);
      return res.status(200).json({
        ok: true, count, occupancy,
        updatedAt: timetable.generatedAt || timetable.storedAt || new Date().toISOString(),
        source: "mongodb-timetables/computing",
      });
    }

    const school = String(req.query?.school || "computing");
    if (!SCHOOLS.has(school)) {
      return res.status(400).json({ ok: false, error: `Unknown school '${school}'. Use: computing, engineering, business` });
    }

    // This is intentionally a fresh database read on every request.  The
    // pooled Mongo client is reused, but the timetable document is not cached.
    const timetable = await loadTimetable(school);
    if (!timetable) {
      return res.status(503).json({ ok: false, error: `Timetable '${school}' is unavailable in MongoDB` });
    }
    return res.status(200).json({
      ok: true,
      school,
      tt: timetable.tt,
      count: timetable.count,
      updatedAt: timetable.generatedAt || timetable.storedAt || new Date().toISOString(),
      generatedAt: timetable.generatedAt,
      source: `mongodb-timetables/${school}`,
    });
  } catch (err) {
    console.error("Mongo timetable read failed:", err?.message || err);
    return res.status(503).json({
      ok: false,
      error: "Timetable data is unavailable in MongoDB",
      message: err?.message || String(err),
    });
  }
};

module.exports.buildCDRoomOccupancy = buildCDRoomOccupancy;
module.exports.countEntries = countEntries;
